# This script guides the user through enabling AWS Cost and Usage Reports (CUR)
# and setting up an Amazon QuickSight user, which are often manual steps
# or require specific console interactions.

echo "--- AWS Billing & QuickSight Prerequisites Setup Guide ---"
echo ""
echo "This script will guide you through crucial setup steps that are often done manually"
echo "or require specific console interactions in AWS."
echo ""
echo "--------------------------------------------------------"
echo "Step 1: Enable AWS Cost and Usage Reports (CUR)"
echo "--------------------------------------------------------"
echo "AWS Cost and Usage Reports (CUR) are essential for this solution as they provide"
echo "the most granular cost data, including data transfer costs."
echo ""
echo "Please follow these steps in the AWS Management Console:"
echo "1.  Go to the AWS Billing dashboard: https://console.aws.amazon.com/billing/"
echo "2.  In the left navigation pane, choose 'Cost & Usage Reports'."
echo "3.  Click 'Create report'."
echo "4.  Provide a 'Report name' (e.g., 'EgressCostOptimizerReport')."
echo "5.  For 'Additional report details', ensure the following are selected:"
echo "    - 'Include resource IDs' (CRITICAL for granular analysis)"
echo "    - 'Enable resource tags' (Highly Recommended for attributing costs)"
echo "    - 'Include public pricing' (Optional, but useful for context)"
echo "6.  For 'S3 bucket', select the S3 bucket created by Terraform for raw logs."
echo "    You can find its name from your Terraform outputs (e.g., 'egress-cost-optimizer-raw-logs-YOUR_SUFFIX')."
echo "    Make sure to confirm the IAM policy for the S3 bucket."
echo "7.  For 'Report path prefix', use a clear prefix (e.g., 'egress-cur/')."
echo "8.  For 'Time granularity', choose 'Hourly' (CRITICAL for detailed analysis)."
echo "9.  For 'Report versioning', choose 'Overwrite existing report' (or 'Create new report version' if you prefer)."
echo "10. For 'Data refresh settings', choose 'Enable automatic refreshes'."
echo "11. Click 'Next' and then 'Review and create'."
echo ""
read -p "Press Enter once you have configured and created the CUR report in the AWS console..."

echo ""
echo "--------------------------------------------------------"
echo "Step 2: Set up Amazon QuickSight User (if not already done)"
echo "--------------------------------------------------------"
echo "Amazon QuickSight is used for visualizing egress cost trends and anomalies."
echo "If you haven't used QuickSight before, you need to set up an account and user."
echo ""
echo "Please follow these steps in the AWS Management Console:"
echo "1.  Go to the Amazon QuickSight console: https://console.aws.amazon.com/quicksight/"
echo "2.  If it's your first time, click 'Sign up for QuickSight'."
echo "3.  Choose your edition (Standard or Enterprise - Enterprise offers more features like row-level security)."
echo "4.  Configure your QuickSight account details (account name, notification email)."
echo "5.  Crucially, in the 'AWS services' section during setup, ensure you grant QuickSight access to:"
echo "    - **Amazon S3:** Select the S3 buckets created by Terraform for raw logs and processed data."
echo "      (e.g., 'egress-cost-optimizer-raw-logs-YOUR_SUFFIX' and 'egress-cost-optimizer-processed-data-YOUR_SUFFIX')."
echo "    - **Amazon Athena:** Grant access to Athena."
echo "    - **AWS Glue:** Grant access to AWS Glue Data Catalog."
echo "    This allows QuickSight to read data from your S3 buckets via Athena/Glue."
echo "6.  Complete the sign-up process."
echo "7.  Once signed up, invite users if necessary."
echo ""
read -p "Press Enter once you have set up your QuickSight account and user..."

echo ""
echo "--- Setup Guide Complete ---"
echo "You have been guided through the manual prerequisites."
echo "You can now proceed with deploying the Terraform infrastructure."
echo ""
echo "Remember to verify your CUR reports are being delivered to the S3 bucket."
echo "You can check the S3 bucket for the 'egress-cur/' prefix (or whatever you set)."
echo ""
